// Mocks generated by Mockito 5.4.4 from annotations
// in muslim_alarm/test/prayer_times/get_times/timers_notifier_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i6;

import 'package:dartz/dartz.dart' as _i3;
import 'package:geolocator/geolocator.dart' as _i4;
import 'package:mockito/mockito.dart' as _i1;
import 'package:muslim_alarm/core/failures/failure.dart' as _i7;
import 'package:muslim_alarm/features/prayer_alarm/domain/entities/timings.dart'
    as _i8;
import 'package:muslim_alarm/features/prayer_alarm/domain/repositories/prayer_alarm_repository.dart'
    as _i2;
import 'package:muslim_alarm/features/prayer_alarm/domain/value_objects/user_location.dart'
    as _i9;

import 'timers_notifier_test.dart' as _i5;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

class _FakePrayerAlarmRepository_0 extends _i1.SmartFake
    implements _i2.PrayerAlarmRepository {
  _FakePrayerAlarmRepository_0(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeEither_1<L, R> extends _i1.SmartFake implements _i3.Either<L, R> {
  _FakeEither_1(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakePosition_2 extends _i1.SmartFake implements _i4.Position {
  _FakePosition_2(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

/// A class which mocks [GetTimesTest].
///
/// See the documentation for Mockito's code generation for more information.
class MockGetTimesTest extends _i1.Mock implements _i5.GetTimesTest {
  MockGetTimesTest() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i2.PrayerAlarmRepository get prayerTimesRepository => (super.noSuchMethod(
        Invocation.getter(#prayerTimesRepository),
        returnValue: _FakePrayerAlarmRepository_0(
          this,
          Invocation.getter(#prayerTimesRepository),
        ),
      ) as _i2.PrayerAlarmRepository);

  @override
  _i6.Future<_i3.Either<_i7.Failure, _i8.Timings>> execute(
          {required _i9.UserLocation? userLocation}) =>
      (super.noSuchMethod(
        Invocation.method(
          #execute,
          [],
          {#userLocation: userLocation},
        ),
        returnValue: _i6.Future<_i3.Either<_i7.Failure, _i8.Timings>>.value(
            _FakeEither_1<_i7.Failure, _i8.Timings>(
          this,
          Invocation.method(
            #execute,
            [],
            {#userLocation: userLocation},
          ),
        )),
      ) as _i6.Future<_i3.Either<_i7.Failure, _i8.Timings>>);
}

/// A class which mocks [LocationServiceTest].
///
/// See the documentation for Mockito's code generation for more information.
class MockLocationServiceTest extends _i1.Mock
    implements _i5.LocationServiceTest {
  MockLocationServiceTest() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i6.Future<_i4.Position> getCurrentPosition() => (super.noSuchMethod(
        Invocation.method(
          #getCurrentPosition,
          [],
        ),
        returnValue: _i6.Future<_i4.Position>.value(_FakePosition_2(
          this,
          Invocation.method(
            #getCurrentPosition,
            [],
          ),
        )),
      ) as _i6.Future<_i4.Position>);
}
